---
deployment:
  tasks:
    # Install dependencies
    - export DEPLOYPATH=/home/goesly/public_html/
    - /bin/cp -R dist/* $DEPLOYPATH
    # Copy server files
    - /bin/cp server.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    # Install Node.js dependencies on server
    - cd $DEPLOYPATH && npm install --production
    # Set proper permissions
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - chmod +x $DEPLOYPATH/server.js